version: 2
jobs:
  test:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: run tests
          command: docker-compose run --rm chirpstack-geolocation-server make test

  deploy:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: compile distributable binaries
          command: docker-compose run --rm chirpstack-geolocation-server make dist
      - run:
          name: upload binaries to s3
          command: aws s3 sync dist/upload s3://builds.loraserver.io/chirpstack-geolocation-server

orbs:
  docker: arribada/docker@0.0.12
workflows:
  publish:
    jobs:
      - docker/publish:
          containerName: lora-geo-server
          context: org-context
          filters:
            branches:
                only: 
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/