baseURL = "https://www.loraserver.io/lora-geo-server/"
languageCode = "en-us"
title = "LoRa Geo Server documentation"
googleAnalytics = "UA-3512995-9"
pygmentsUseClasses = true

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "Install"
    identifier = "install"
    url = "/install/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-cogs'></i>"
    name = "Backends"
    identifier = "backends"
    url = "/backends/"
    weight = 3

[[menu.main]]
    pre = "<i class='fas fa-chart-line'></i>"
    name = "Metrics"
    identifier = "metrics"
    url = "/metrics/"
    weight = 4

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 5

[params]
    version = "3.2.0"
